version: 2
jobs:
    build:
        docker:
        - image: circleci/node:12.14-browsers

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run:
                  name: Install Dependancies
                  command: yarn

            - save_cache:
                  key: v1-dependencies-{{ checksum "package.json" }}
                  paths:
                      - node_modules
                      - functions/node_modules

            - run:
                  name: Build
                  command: npm run build

            - run:
                  name: Deploy
                  command: npm run deploy
