name: Build Website
run-name: Build Website

on:
    push:
        paths:
            - '.github/workflows/website.yaml'
            - 'website/**'

jobs:
    build:
        name: Build NPM Project
        runs-on: ubuntu-latest
        container: node
        steps:
            - name: Clone Repository
              uses: ztimson/actions/clone@develop

            - name: Install Dependencies
              run: npm i
              working-directory: website

            - name: Build Project
              run: npm run build
              working-directory: website

            - name: Upload Artifacts
              if: ${{inputs.artifacts}} != "false"
              uses: actions/upload-artifact@v3
              with:
                  name: website
                  path: website/dist
                  retention-days: 7

    tag:
        name: Tag Version
        needs: build
        runs-on: ubuntu-latest
        container: node
        steps:
            - name: Clone Repository
              uses: ztimson/actions/clone@develop

            - name: Get Version Number
              run: echo "VERSION=$(cat package.json | grep version | grep -Eo ':.+' | grep -Eo '[[:alnum:]\.\/\-]+')" >> $GITHUB_ENV
              working-directory: website

            - name: Tag Version
              uses: ztimson/actions/tag@develop
              with:
                  tag: ${{env.VERSION}}